//= output "DONE\n"

fun main() {
  do {
    try foo();
  } catch x: Array<Bar> {
    assert(x.length() == 5);
    println("DONE");
  }
}

fun foo() throws {
  do {
    throw arrayFill::<Bar>(5, nil);
  } catch x: Array<Foo> {
    fatalError("should not be caught");
  }
}

class Foo
class Bar