//= error unexpected

fun main() {
    let val = try! foo();
    print(val.toString());
}

fun foo() throws -> Int {
    throw "foo";
}